### PR TITLE
Update French & English translations about trusted device

### PR DESCRIPTION
**Pull request by jmsche**
**Description**

Hi, this PR updates the French translation file to something like "I'm on a trusted device" rather than "I'm on a trusted computer", because... well, not all devices are computers :)

Maybe I should update the English file as well?

### CODE REVIEW

**Comment by jmsche** [comment]
CI failure seems unrelated; tests do pass

**Comment by scheb** [comment]
Agree. Could you update EN as well?

(Fixed the build error, btw.)

**Comment by jmsche** [comment]
Done :)

**Review by maxhelias — APPROVED** [review]

**Comment by scheb** [comment]
Thanks for contributing!

**Pull request merged**
