### PR TITLE
Avoid deprecation warnings in Symfony 5.3

### PR DESCRIPTION
**Pull request by Seldaek**
Not sure if method_exists is typically the way you'd do that, but hopefully this works.

### CODE REVIEW

**Comment by scheb** [comment]
Obviously this hasn't been covered in #89 :/ There's obviously a whole bunch of these `isMasterRequest` still left: https://github.com/scheb/2fa/search?q=getMasterRequest

The `method_exists` approach is also what I'd use. A reference implementation is [here](https://github.com/scheb/2fa/blob/5.x/src/bundle/Security/TwoFactor/Provider/TwoFactorProviderPreparationListener.php#L117-L126). Tests would need an update as well, since Symfony 5.3+ builds use the new code path.

If you could add `Compatibility for Symfony >= 5.3` as a comment would be wonderful, helps me to find these things easily once I'm able to clean it up in the next major version.

**Comment by Seldaek** [comment]
Sure I'll try to get this done next week.

**Comment by scheb** [comment]
No rush :)

I'd do it myself, but the new job is very demanding, currently no motivation to do coding after work :/

**Comment by Seldaek** [comment]
Ok I think it's good to go :)

**Comment by scheb** [comment]
Awesome, thank you Jordi!

**Pull request merged**
