### PR TITLE
Document how to bypass 2FA entirely in a given context

### PR DESCRIPTION
**Pull request by Seldaek**
This is partially a question too.. is this the best way? 

I first tried setting up a custom 2fa condition class but I did not have access to the Passport via the AuthenticationContextInterface, so it made things tricky as I couldn't easily add a TwoFactorBypassBadge or something to look at. I had to use the token, then when looking at internals further I found out that I may not even need a custom condition at all if I'm modifying the token already.. But IMO a passport badge would be more natural in the new authenticator.

### CODE REVIEW

**Comment by scheb** [comment]
So you can't make the decision whether 2fa should be applied or nor based on the security token, but you'd want to make it based on the authenticator that was used to generate that security token? I guess you have multiple authenticators all using the same security token class. Do I understand that right?

**Comment by Seldaek** [comment]
Yes that is correct. I could for sure also create a new token, but IMO the token should be used to represent a user and shouldn't have to change here. The passport/badge system is used to configure the auth flow and so it would be much more natural to do it at that level. This could be a feature request I guess, but I needed a solution now, and this attribute on the token appears to work :)

**Comment by scheb** [comment]
Attribute on token is in fact a valid solution imo.

I'd need to look into what the flow with the new authenticator system is like. The decision is based on the token mostly because that was the only way to distinguish authentication methods in the classic security system.

**Comment by Seldaek** [comment]
Yup works fine for current setup. In a future world where there is only authenticator. I think having a badge makes more sense, actually this is kinda covered by https://github.com/scheb/2fa/issues/67 already - if the TwoFactorAuthBadge was part of this bundle and recognized by it, then I could have added the badge, called markResolved() on it already in the authenticator to make it skip the badge auth step.

**Comment by scheb** [comment]
I'll add a note that this approach is only working with the authenticator system :)

If the PR for Symfony is accepted I can include the passport in the `AuthenticationContext`. Then you have a badge on the passport and check for it in a custom condition. In my opinion that would be the clean solution.

**Pull request merged**
