### PR TITLE
[Docs] Change Google entity code example

### PR DESCRIPTION
**Pull request by gnito-org**
It's a change that PHPStorm Inspections recommended in my User entity.

### CODE REVIEW

**Comment by stephanvierkant** [comment]
And what if your `googleAuthenticatorSecret` is `00000`? Not sure if that is even possible, but (explicit) casting strings to boolean doesn't look that much better than implicit casting by using an if condition. See http://phpsadness.com/sad/47

What about `$this->googleAuthenticatorSecret !== null`?

**Comment by scheb** [comment]
Changing it to a boolean cast wouldn't significantly change the logic. `null !== $this->googleAuthenticatorSecret` (Yoda Condition style) would actually be a change that I'd accept in :)

**Comment by gnito-org** [comment]
Ok, I will modify the PR.

Just want to say that ``00000`` is not an issue because the secret is always a [string](https://github.com/scheb/2fa-google-authenticator/blob/fe0db75570b5f2de061e6c8446775ae90809a4e9/Security/TwoFactor/Provider/Google/GoogleAuthenticator.php#L44).

The current ``return $this->googleAuthenticatorSecret ? true : false;`` will also return false on a numeric ``00000``.

**Comment by scheb** [comment]
Thanks for updating that so swiftly :)

**Pull request merged**
