### PR TITLE
Fix Google Authenticator website URL

### PR DESCRIPTION
**Pull request by osavchenko**
**Description**

Update Google Authenticator website URL

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

**Comment by scheb** [comment]
There's another occurrence of that URL in totp.rst, would you please update that one as well?

**Comment by osavchenko** [comment]
Sure, done.
Also, I checked other URLs and found that one of the Symfony doc URLs got a redirect. I'm not sure if that redirect is ok or maybe there should be another URL. So, I changed the component version for now. Could you please advise how to fix this doc issue?

**Comment by scheb** [comment]
The Symfony Docs URLs do not redirect for me. `current` would be what I'd want to keep. So please revert that.

**Comment by scheb** [comment]
Thank you for contributing :)

**Pull request merged**
